config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  get 'welcome/index'
  root "welcome#index"
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true
    def self.look_up(ticker_symbol)
        client = IEX::Api::Client.new(
                    publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
                     endpoint: 'https://sandbox.iexapis.com/v1'
                    )
        begin
        new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
          return nil
        end
    end

  def self.db_search(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_exists?(ticker_symbol)
    stock = Stock.db_search(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_limit
    stocks.count < 10
  end

  def can_track?(ticker_symbol)
   under_limit && !stock_exists?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Annonymous"
  end

  def self.search(param)
    param.strip!
    to_return = (email_match(param) + fname_match(param) + lname_match(param)).uniq
    return nil unless  to_return
    to_return
  end

  def self.email_match(param)
    matches('email',param)
  end

  def self.fname_match(param)
    matches('first_name', param)
  end

  def self.lname_match(param)
    matches('last_name', param)
  end

  def self.matches(field,param)
    where("#{field} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id}
  end

  def not_friends?(f_id)
    !self.friends.where(id: f_id).exists?
  end




end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])

  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice]= "following User"
    elsif
      flash[:alert]= "There was an error occured"
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Stopped following"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        if params[:stock].present?
            @stock = Stock.look_up(params[:stock])
            if @stock
                respond_to do |format|
                    format.js { render partial: 'users/result'}
                end
            else
                #binding.pry
                respond_to do |format|
                    flash.now[:alert] = "please enter a valid symbol to search"
                    format.js { render partial: 'users/result'}
                end
            end
        else
            respond_to do |format|
                flash.now[:alert] = "please enter a symbol to search"
                format.js { render partial: 'users/result'}
            end
        end
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.db_search(params[:ticker])
    if stock.blank?
      # binding.pry
      stock = Stock.look_up(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice]= "Stock #{stock.name} successfully added to your portfolio"
    redirect_to my_portfolio_path
  end
  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user, stock_id: stock).first
    user_stock.destroy
    flash[:notice]="Stock removed successfully"
    redirect_to my_portfolio_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def my_portfolio
    @user = current_user
    @track_stocks =  current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @track_stocks = @user.stocks
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friendresult'}
        end
      else
        #binding.pry
        respond_to do |format|
          flash.now[:alert] = "please enter a valid username or email to search"
          format.js { render partial: 'users/friendresult'}
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "please enter a name or email to search"
        format.js { render partial: 'users/friendresult'}
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if !current_user
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<% if !@friends.empty?%>
  <div class="row">
    <div class="col-9">

      <table class="table table-hover table-bordered">
        <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First name</th>
          <th scope="col">Last name</th>
          <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        <% @friends.each do |friend| %>
          <tr>

            <th scope="row"> <%=friend.email %></th>
            <td><%=friend.first_name %></td>
            <td><%=friend.last_name  %></td>
            <td> <%= link_to 'View Profile', user_path(friend),
                             class: "btn btn-sm btn-success "%>
              <%= link_to 'Unfriend', friendship_path(friend), method: :delete, data: {confirm: "Are you sure?"},
                             class: "btn btn-sm btn-warning "%> </td>

          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
<% end %>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <a href="#" class="close" data-dismiss="alert"> &#215; </a>

  <%= notice %>
</div>

<% elsif alert%>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">

    <a href="#" class="close" data-dismiss="alert"> &#215; </a>
    <%= alert %>
  </div>
<%end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <strong>
      <%if current_user %>
        <%= link_to "Finance Tracker",  root_path, class: "navbar-brand" %>
      <%else %>
        <%= link_to "Finance Tracker",  new_user_session_path , class: "navbar-brand" %>
      <% end %>
        </strong>
    <% if current_user %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
          <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
          <%= link_to "My Friends", my_friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to edit_user_registration_path , class: "nav-link" do %>
            <%= fa_icon 'edit' %> Edit Profile
          <% end %>
        </li>


        <li class="nav-item name">
          <%= fa_icon 'user' %>
          <%= current_user.full_name %>
        </li>
        <li class="nav-item logoutpd">
          <%= link_to "Logout", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete %>
        </li>
      </ul>
      <form class="d-flex ml-auto">
        <input class="form-control me-2 " type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>

  <body>


  <%= render 'layouts/navbar' %>
  <div class="container">
  <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<% if !@track_stocks.empty?%>
<div class="row">
  <div class="col-9">

<table class="table table-hover table-bordered">
  <thead>
  <tr>
    <th scope="col">Ticker</th>
    <th scope="col">name</th>
    <th scope="col">Price</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @track_stocks.each do |stock| %>
  <tr>

      <th scope="row"> <%=stock.ticker %></th>
      <td><%=stock.name %></td>
      <td><%=stock.last_price  %></td>

      <td>

        <% if current_user.can_track?(stock.ticker) %>
          <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: stock.ticker) ,
                      class: "btn btn-xs btn-success", method: :post%>
        <% elsif current_user.id != @user.id %>
      <span class="badge badge-secondary ">
        You are already tracking
        <% if !current_user.under_limit %>
          10 stocks
        <% elsif current_user.stock_exists?(stock.ticker) %>
          this stock
          <% end %>
      </span>
        <% end %>



        <% if current_user.id == @user.id %>
        <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: "Are you sure?"},
                                 class: "btn btn-sm btn-warning "%>
        <% end %>
          </td>


  </tr>
  <% end %>
  </tbody>
</table>

  </div>
</div>
  <% else %>
  <div class="container">
    <br>
    <p class="lead">this user is not following any stocks</p>
  </div>
<% end %>

app/views/users/_friendresult.html.erb
<%= render 'layouts/messages' %>

<% if @friends %>
  <div class="card card-header col-9">
    <table class="col-md-12 ">
      <tbody>
  <% @friends.each do |friend| %>
    <tr>
      <td><strong> Full name </strong> <%= friend.full_name%></td>
      <td><strong> Email </strong> <%= friend.email%></td>
      <td><strong> Action </strong> <%= link_to "View Profile", user_path(friend) , class: "btn btn-sm btn-success"%>
                            <% if current_user.not_friends?(friend.id) %>
                            <%=link_to "Follow Friend", friendships_path(friend: friend) , class: "btn btn-sm btn-success", method: :post %></td>
                            <%else %>
                              <span class="badge bg-secondary">
                                Already added
                              </span>
                            <% end %>
          </tr>
      <%end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friendresult.js.erb
document.querySelector('#result').innerHTML= '<%= j render 'users/friendresult.html' %>'

app/views/users/_result.html.erb
<%= render 'layouts/messages' %>

<% if @stock %>
  <div class="card card-header col-9">

    <strong> Symbol: </strong> <%= @stock.ticker %>
    <strong> Name: </strong> <%= @stock.name %>
    <strong> Last Price: </strong> <%= @stock.last_price %>

    <% if current_user.can_track?(@stock.ticker) %>
    <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker) ,
                                  class: "btn btn-xs btn-success col-3", method: :post%>
    <% else %>
      <span class="badge badge-secondary ">
        You are already tracking
        <% if !current_user.under_limit %>
          10 stocks
        <% elsif current_user.stock_exists?(@stock.ticker) %>
          this stock
          <% end %>
      </span>
    <% end %>
    </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#result').innerHTML= '<%= j render 'users/result.html' %>'

app/views/users/my_friends.html.erb
<br>
<h1>Friends</h1>
<br><br>
<h3>Search friends</h3>

<%= form_tag 'search_friend', remote: true, method: :get do %>
  <div class="form-group row">
    <div class="col-sm-9 norp">
      <%= text_field_tag :friend, params[:friend], placeholder: "friends name", autofocus: true, class: "form-control form-control-lg"%>

    </div>
    <div class="col-sm-3 nolp">
      <%= button_tag type: :submit , class: "btn btn-success" do %>
        <%= fa_icon 'search 2x'%>
      <% end %>
    </div>
  </div>

<% end %>

<div id="result">

</div>
<br>
<%= render 'friends/list' %>

app/views/users/my_portfolio.html.erb
<br>
<h1>Portfolio</h1>
<br><br>
<h3>Search Stoks</h3>

<%= form_tag 'search_stock', remote: true, method: :get do %>
    <div class="form-group row">
    <div class="col-sm-9 norp">
    <%= text_field_tag :stock, params[:stock], placeholder: "ticker sybmol", autofocus: true, class: "form-control form-control-lg"%>
    
    </div>
    <div class="col-sm-3 nolp">
    <%= button_tag type: :submit , class: "btn btn-success" do %>
        <%= fa_icon 'search 2x'%>
    <% end %>
    </div>
    </div>

<% end %>

<div id="result">

</div>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2> User Details </h2>

<div class="card card-header col-9">
  <table class="col-md-12 ">
    <tbody>

      <tr>
        <td><strong> Full name </strong> <%= @user.full_name%></td>
        <td><strong> Email </strong> <%= @user.email%></td>
        <td><strong> Action </strong> <% if current_user.not_friends?(@user.id) %>
            <%=link_to "Follow Friend", friendships_path(friend: @user) , class: "btn btn-sm btn-success", method: :post %></td>
          <%else %>
                              <span class="badge bg-secondary">
                                Already added
                              </span>
          <% end %>
          </tr>

    </tbody>
  </table>
</div>
<br>
<%= render 'stocks/list' %>

app/views/welcome/index.html.erb
<div class="container-fluid">
<h1>Welcome</h1>

<!-- Example single danger button -->
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <p><br><strong>Hey There</strong> Welcome <3 </p>
</div>


</div>